allow-uncaught: false
color: true
exit: false # could be expressed as "no-exit: true"
extension: ["js", "cjs", "mjs"]
ignore:
  - "./node_modules"
node-option:
  - "unhandled-rejections=strict" # without leading "--", also V8 flags
spec:
  - "*.test.js" # the positional arguments!
full-trace: true
package: "./package.json"
parallel: true
